### ISSUE TITLE
Generation fails due to some .png images having their extension in uppercase.

### ISSUE THREAD

**Issue by Pshy0** [1010todd/Endless-Endless-Sky#2]
![image](https://github.com/1010todd/Endless-Endless-Sky/assets/44928041/e2671b47-effe-495d-a19e-0ef2ed66d723)

The script fails on filesystems where file names are case sensitive due to some files having the `.PNG` extension instead of `.png`.

**Comment by 1010todd** [comment]
I don't have a linux machine to test right now but hopefully [275f4e8](https://github.com/1010todd/Endless-Endless-Sky/commit/275f4e8cd8221c87a4b43a5b8985ea7779289b09) should fix it.

Update 2024-03-27:
Finally got a chance to actually test it and nope, that didn't fix it. And my god the script is horrid, just tried fixing that and now there's ten more errors popping up.

**Comment by 1010todd** [comment]
Turns out to be more of a pain to fix in the script than I imagined so I renamed the image extensions instead. Should be fine for now.
